version: '3'

services:

  mongo-express:
    image: mongo-express
    env_file:
      - express_conf.env
    ports:
      - "8999:8081"

  mongo:
    image: mvertes/alpine-mongo

  redis:
    image: redis:alpine

  bot:
    depends_on:
      - redis
      - mongo
    build: .
    restart: always
    env_file:
      - bot_config.env
    volumes:
      - ./logs:/app/logs
