version: '3'

services:

  mongo-express:
    image: mongo-express
    env_file:
      - express_conf.env
    ports:
      - "8999:8081"

  mongo:
    image: mvertes/alpine-mongo

  redis:
    image: library/redis:6.0.6
    command: redis-server /usr/local/etc/redis/redis.conf
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf

  bot:
    depends_on:
      - redis
      - mongo
    build: .
    restart: always
    env_file:
      - bot_config.env
    volumes:
      - ./:/app
      - ./logs:/app/logs
