version: '3'

services:

  mongo:
    image: mvertes/alpine-mongo

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  bot:
    build: .
    restart: always
    env_file:
      - bot_config.env