version: '3'

services:

  mongo:
    image: mvertes/alpine-mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  bot:
    build: .
    restart: always
    env_file:
      - bot_config.env
    links:
      - redis:redis
      - mongo:mongo